name: Prebuild
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux
            arch: x64
          - os: ubuntu-24.04-arm
            platform: linux
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: Build / ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - uses: holepunchto/actions/setup-llvm@v1
      - run: sudo apt install -y libgtk-4-dev libwebkitgtk-6.0-dev
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          upload: true
  merge:
    runs-on: ubuntu-latest
    needs: prebuild
    name: Merge
    steps:
      - uses: holepunchto/actions/merge-prebuilds@v1
